# Використовуйте офіційний образ Nginx
FROM nginx:latest

# Видаляємо стандартний конфігураційний файл Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Копіюємо файли HTML, CSS та JavaScript у контейнер
COPY frontend /usr/share/nginx/html

# Копіюємо конфігураційний файл Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Відкриваємо порт 80
EXPOSE 80
