# Generated by Django 4.2.6 on 2023-10-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('data_analytics', models.BooleanField(default=False)),
                ('service_analytics', models.BooleanField(default=False)),
                ('voice_analytics', models.BooleanField(default=False)),
                ('queue_stats', models.BooleanField(default=False)),
                ('voice_stats', models.BooleanField(default=False)),
                ('video', models.BooleanField(default=False)),
                ('smart_access', models.BooleanField(default=False)),
                ('diagrams', models.BooleanField(default=False)),
            ],
        ),
    ]
